In [9]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from scipy import stats

diabetes=datasets.load_diabetes()
x=diabetes.data
y=diabetes.target

x2=sm.add_constant(x)
est=sm.OLS(y,x2)
est2=est.fit()
print(est2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.518
Model:                            OLS   Adj. R-squared:                  0.507
Method:                 Least Squares   F-statistic:                     46.27
Date:                Mon, 24 Feb 2020   Prob (F-statistic):           3.83e-62
Time:                        10:35:07   Log-Likelihood:                -2386.0
No. Observations:                 442   AIC:                             4794.
Df Residuals:                     431   BIC:                             4839.
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        152.1335      2.576     59.061      0.000     147.071     157.196
x1           -10.0122     59.749     -0.168      0.867    -127.448     107.424
x2          -239.8191     61.222     -3.917      0.000    -360.151    -119.488
x3           519.8398     66.534      7.813      0.000     389.069     650.610
x4           324.3904     65.422      4.958      0.000     195.805     452.976
x5          -792.1842    416.684     -1.901      0.058   -1611.169      26.801
x6           476.7458    339.035      1.406      0.160    -189.621    1143.113
x7           101.0446    212.533      0.475      0.635    -316.685     518.774
x8           177.0642    161.476      1.097      0.273    -140.313     494.442
x9           751.2793    171.902      4.370      0.000     413.409    1089.150
x10           67.6254     65.984      1.025      0.306     -62.065     197.316
==============================================================================
Omnibus:                        1.506   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.471   Jarque-Bera (JB):                1.404
Skew:                           0.017   Prob(JB):                        0.496
Kurtosis:                       2.726   Cond. No.                         227.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [10]:
df=pd.read_csv('HR_Comma_Sep.csv')
df.shape
## drop department columns
#create dummy variables for salary
subdf=df.drop(['sales','last_evaluation','number_project'], axis=1)
subdf
subdf2=pd.get_dummies(subdf, prefix='salary', drop_first=True)
subdf2

,satisfaction_level,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,salary_low,salary_medium
0,0.38,157,3,0,1,0,1,0
1,0.80,262,6,0,1,0,0,1
2,0.11,272,4,0,1,0,0,1
3,0.72,223,5,0,1,0,1,0
4,0.37,159,3,0,1,0,1,0
...,...,...,...,...,...,...,...,...
14994,0.40,151,3,0,1,0,1,0
14995,0.37,160,3,0,1,0,1,0
14996,0.37,143,3,0,1,0,1,0
14997,0.11,280,4,0,1,0,1,0
14998,0.37,158,3,0,1,0,1,0

In [11]:
from sklearn.model_selection import train_test_split
x=subdf2.drop('left', axis=1)

y=subdf2.left
train_x, test_x, train_y, test_y=train_test_split(x, y, test_size=0.33, random_state=42)

In [14]:
train_x2=sm.add_constant(train_x)
ols=sm.OLS(train_y,train_x2)
ols2=ols.fit()
print(ols2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   left   R-squared:                       0.213
Model:                            OLS   Adj. R-squared:                  0.212
Method:                 Least Squares   F-statistic:                     387.4
Date:                Mon, 24 Feb 2020   Prob (F-statistic):               0.00
Time:                        10:45:09   Log-Likelihood:                -4477.0
No. Observations:               10049   AIC:                             8970.
Df Residuals:                   10041   BIC:                             9028.
Df Model:                           7
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                     0.2827      0.024     11.666      0.000       0.235       0.330
satisfaction_level       -0.6313      0.015    -41.260      0.000      -0.661      -0.601
average_montly_hours      0.0005   7.63e-05      6.022      0.000       0.000       0.001
time_spend_company        0.0322      0.003     12.253      0.000       0.027       0.037
Work_accident            -0.1517      0.011    -14.190      0.000      -0.173      -0.131
promotion_last_5years    -0.1138      0.026     -4.426      0.000      -0.164      -0.063
salary_low                0.2141      0.014     14.987      0.000       0.186       0.242
salary_medium             0.1356      0.014      9.443      0.000       0.107       0.164
==============================================================================
Omnibus:                      939.642   Durbin-Watson:                   1.958
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1187.505
Skew:                           0.829   Prob(JB):                    1.37e-258
Kurtosis:                       2.709   Cond. No.                     1.56e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.56e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [15]:
train_x2=sm.add_constant(train_x)
logit=sm.Logit(train_y,train_x2)
logit2=logit.fit()
print(logit2.summary())

Optimization terminated successfully.
         Current function value: 0.433479
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:                   left   No. Observations:                10049
Model:                          Logit   Df Residuals:                    10041
Method:                           MLE   Df Model:                            7
Date:                Mon, 24 Feb 2020   Pseudo R-squ.:                  0.2098
Time:                        10:57:38   Log-Likelihood:                -4356.0
converged:                       True   LL-Null:                       -5512.6
Covariance Type:            nonrobust   LLR p-value:                     0.000
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                    -1.8407      0.208     -8.844      0.000      -2.249      -1.433
satisfaction_level       -3.8167      0.112    -34.225      0.000      -4.035      -3.598
average_montly_hours      0.0018      0.001      3.419      0.001       0.001       0.003
time_spend_company        0.2298      0.018     12.543      0.000       0.194       0.266
Work_accident            -1.4708      0.106    -13.856      0.000      -1.679      -1.263
promotion_last_5years    -1.3254      0.299     -4.435      0.000      -1.911      -0.740
salary_low                2.1203      0.162     13.092      0.000       1.803       2.438
salary_medium             1.5922      0.163      9.773      0.000       1.273       1.912
=========================================================================================